# Generated by Django 4.0.2 on 2022-02-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=150)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('lastEdited', models.DateTimeField(auto_now=True)),
                ('fields', models.TextField()),
                ('authorId', models.ForeignKey(default='Не известно', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('authorId', models.ForeignKey(default='Не известно', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('questionnaireId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.questionnaire')),
            ],
        ),
    ]
