# Generated by Django 4.0.2 on 2022-02-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastorage',
            old_name='authorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='datastorage',
            old_name='questionnaireId',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='authorId',
            new_name='author',
        ),
    ]
