# Generated by Django 4.0.2 on 2022-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_rename_authorid_datastorage_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='createdDate',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='lastEdited',
            field=models.DateTimeField(),
        ),
    ]
